<a href="https://colab.research.google.com/github/lilychen0505/BDSE19_PROJECT/blob/JuliusChiang/Scrape_yahoo_car_url0720ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import re
import time
import random
!pip install selenium
!apt-get update 
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
from selenium import webdriver

In [ ]:
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
wd = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

In [20]:
#df = pd.DataFrame(columns=['mid', 'img', 'w', 'h', 'auto_build_year', 'auto_drive_km', 'title',
#       'ptype', 'utime', 'promobg', 'promokit', 'ad_map_display', 'tag',
#       'ad_summary', 'desc', 'advv', 'location', 'olink', 'poster', 'lat',
#       'lng', 'link', 'price', 'mlink'])
for i in range(1,4): #試爬3頁
    headers = {
        'authority': 'tw.usedcar.yahoo.com',
        'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
        'x-requested-with': 'XMLHttpRequest',
        'sec-ch-ua-mobile': '?0',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'accept': '*/*',
        'origin': 'https://tw.usedcar.yahoo.com',
        'sec-fetch-site': 'same-origin',
        'sec-fetch-mode': 'cors',
        'sec-fetch-dest': 'empty',
        'referer': 'https://tw.usedcar.yahoo.com/search?catb=&catid=&areab=&kw=&cata=000000515224&areaa=tw',
        'accept-language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7',
        'cookie': 'F=d=qstBU9c9vvxjvFcuF.aNWlBYfnJjq6zogJsrva2jDgG4sxLGReU0XayeEyvt.5svULuV6UoCBlBgiw1NaWrlUyiHqIIOuAyXp5cK1g--; Y=v=1&n=7cqegpqatbjr6&l=0szsztwvw/o&p=f30vvtw00000000&iz=234&r=g3&intl=tw; A1=d=AQABBD3y9V0CEKHqjN5Kz19O6CHrePThQ9oFEgEABAL7tWCeYb2pQDIB_eMAAAcIz7YkXSKsyCkID2JBYsmJYttMpsNqYnTWtQkBBwoBMg&S=AQAAAo-0eYyRgP7YVAHp9nAKTkg; A3=d=AQABBD3y9V0CEKHqjN5Kz19O6CHrePThQ9oFEgEABAL7tWCeYb2pQDIB_eMAAAcIz7YkXSKsyCkID2JBYsmJYttMpsNqYnTWtQkBBwoBMg&S=AQAAAo-0eYyRgP7YVAHp9nAKTkg; GUC=AQEABAJgtfthnkIciQRJ; OTH=v=1&d=eyJraWQiOiIwMTY0MGY5MDNhMjRlMWMxZjA5N2ViZGEyZDA5YjE5NmM5ZGUzZWQ5IiwiYWxnIjoiUlMyNTYifQ.eyJjdSI6eyJndWlkIjoiRE5ZUTZSRU1RTkQyRUJES0tNWEZOVEVLSkEiLCJwZXJzaXN0ZW50Ijp0cnVlLCJzaWQiOiJsOGNNY0tveG53bVUifX0.2EYT0ScOGxNrIFaWRh2nnitY95RBd-9r5WfJQdFiNCt1P--oaXhgBLnp_GRwx_L-JP2fZ-XXRTiNDA5YGyGkLd0UnVGCS4BRv98ZhVPEDE5qUJD7JIHkzbkplxbVvdhrtGUIusr0F_9iXE1KOgzVm0Gc0tYGYaxMa3V7fAgoZGg; T=af=JnRzPTE2MjM5NDI1MzAmcHM9Mk56aTdoNVg1b1hDMjQzVHFaWng4Zy0t&d=bnMBeWFob28BZwFETllRNlJFTVFORDJFQkRLS01YRk5URUtKQQFhYwFBTkZUTGdmagFhbAFhMjkyOTM2NTYBc2MBZGVza3RvcF93ZWIBZnMBVzFWdFhDSmRpaXBkAXp6AUNXMnlnQkE3RQFhAVFBRQFsYXQBQ1cyeWdCAW51ATA-&sk=DAAxWPw2WNIIhn&kt=EAAAo4QrTVB45fAc.de4xMvSA--~I&ku=FAAIXURZn9Z2DL3jvRZ88te4f4YA4lvCDJspeGSrF53SdKhB6ebUYsJgT8Dj9Sog.0Qtz4QIUsfqoAhAa.TagsYZWTao1SH6dwVJmJhUZShKDBnWuK7.WBe4nUTJ6iEdj8f1M5J3mo3YCIfnYvye5SHVj4FK7jKipUWdwCV9jmKgPY-~D; PH=fn=ZYksoDH1D2xNMBPdPSLo&l=zh-Hant-TW&i=tw; B=2ji5c49ei9dmf&b=4&d=M74x4mltYFH121rv4s6U&s=11&i=YkFiyYli20ymw2pidNa1; APID=UPc7689826-d35a-11eb-99a7-0a4d72fbd805; A1S=d=AQABBD3y9V0CEKHqjN5Kz19O6CHrePThQ9oFEgEABAL7tWCeYb2pQDIB_eMAAAcIz7YkXSKsyCkID2JBYsmJYttMpsNqYnTWtQkBBwoBMg&S=AQAAAo-0eYyRgP7YVAHp9nAKTkg&j=WORLD; ucs=tr=1625022552000; cmp=t=1624936157&j=0; _ga=GA1.3.1646580260.1624975082; _gid=GA1.3.1545869013.1624975082',
    }

    data = {
      'kw': '',
      'catid': '',
      'undedup': '0',
      'unspc': '0',
      'cata': '000000515224',
      'catb': '',
      'pricea': '',
      'priceb': '',
      'items': '',
      'areaa': 'tw',
      'areab': '',
      'areac': '',
      'sort': '0',
      'total': '7964',
      f'cp': {i},
      'ppa': '30',
      'pa': '10',
      'type': 'srplist',
      'vmode': '0',
      'action': 'srplistquery'
    }

#   car_info = requests.post('https://tw.usedcar.yahoo.com/search/search_services', headers=headers, data=data).json()
#    df1 = pd.json_normalize(car_info['data'][1:])
#    df = pd.concat([df,df1],axis=0)

In [4]:

#法二: 因有機車等雜訊，僅爬取汽車類，用網址分開爬取
link_all = []
number = list(range(2,30))

for i in range(1,3):
    #四門房車/旅行車/掀背車
    url = f'https://tw.usedcar.yahoo.com/search?catb=&areab=&kw=&cata=000000515224&areaa=tw#!kw=&catid=&undedup=0&unspc=0&cata=000000515224&catb=000000515235&pricea=&priceb=&items=&areaa=tw&areab=&areac=&sort=0&cp={i}&ppa=30&pa=10&vmode=0'
    #雙門轎跑/跑車/敞篷車
    #url2 = f'https://tw.usedcar.yahoo.com/search?catb=&areab=&kw=&cata=000000515224&areaa=tw#!kw=&catid=&undedup=0&unspc=0&cata=000000515224&catb=15020649&pricea=&priceb=&items=&areaa=tw&areab=&areac=&sort=0&cp={i}&ppa=30&pa=10&vmode=0'
    #休旅車/吉普車
    #url3 = f'https://tw.usedcar.yahoo.com/search?catb=&areab=&kw=&cata=000000515224&areaa=tw#!kw=&catid=&undedup=0&unspc=0&cata=000000515224&catb=000000515236&pricea=&priceb=&items=&areaa=tw&areab=&areac=&sort=0&cp={i}&ppa=30&pa=10&vmode=0'
    #商用車/貨卡車
    #url4 = f'https://tw.usedcar.yahoo.com/search?catb=&areab=&kw=&cata=000000515224&areaa=tw#!kw=&catid=&undedup=0&unspc=0&cata=000000515224&catb=000000515237&pricea=&priceb=&items=&areaa=tw&areab=&areac=&sort=0&cp={i}&ppa=30&pa=10&vmode=0'
    wd.get(url)
    #wd.get(url1 + url2 + url3 + url4)
    time.sleep(5)
    for j in number:
        for link in wd.find_elements_by_xpath(f'//*[@id="ycsrpresult"]/li[{j}]/div/div[2]/p[1]/a'):
            link_all.append(link.get_attribute('href')) 
wd.close()

In [44]:
df1 = []
number = list(range(2,30))

for i in range(1,3):
    #四門房車/旅行車/掀背車
    url1 = f'https://tw.usedcar.yahoo.com/search?catb=&areab=&kw=&cata=000000515224&areaa=tw#!kw=&catid=&undedup=0&unspc=0&cata=000000515224&catb=000000515235&pricea=&priceb=&items=&areaa=tw&areab=&areac=&sort=0&cp={i}&ppa=30&pa=10&vmode=0'
    wd.get(url1)
    time.sleep(5)
    for j in number:
        for link in wd.find_elements_by_xpath(f'//*[@id="ycsrpresult"]/li[{j}]/div/div[2]/p[1]/a'):
            link_all.append(link.get_attribute('href')) 
wd.close()
for url1 in link_all[:5]:
    #print(url)
    r=requests.get(url1,headers=headers)
    soup=BeautifulSoup(r.text,'lxml')     
    #物件編號
    car_id = []
    idnumber = soup.find_all('li',class_='last mei-g')
    idnumber1 = BeautifulSoup(str(idnumber), 'html.parser')
    idnumber2 = idnumber1.find_all('div',class_='mei-u dcontent')
    for z in idnumber2 :
        z = z.text.strip()
        car_id = z
    #車款
    model = soup.find_all('div',class_='itemhd')
    model1 = BeautifulSoup(str(model), 'html.parser')
    model2 = model1.find_all('a')[2]
    car_model = model2.text.strip()    
    #車輛價格
    car_price = []
    details = soup.find_all('li',class_='mei-g')
    details1 = BeautifulSoup(str(details), 'html.parser')
    details2 = details1.find_all('em',class_='price')
    for z in details2 :
        z = z.text.strip()
        car_price = z
    #刊登標題
    car_title = []
    title = soup.find_all('div', class_='prightn mei-u')
    title1 = BeautifulSoup(str(title), 'html.parser')
    title2 = title1.find_all('div',class_='rthd')
    for z in title2 :
        z = z.text.strip()  
        car_title = z  
    #車商名
    car_dealer = []    
    seller = soup.find_all('div',class_='pleftn mei-u')
    seller1 = BeautifulSoup(str(seller), 'html.parser')
    seller2 = seller1.find_all('div',class_='mbd')
    for z in seller2 :
        car_dealer.append(z.text.strip().split('\n')[0])
    #車商地址 
    car_address = []
    address = soup.find_all('li',class_='mei-g')
    address1 = BeautifulSoup(str(address), 'html.parser')
    address2 = address1.find('em', itemprop="address")
    car_address.append(address2.text.strip()) 
    #出廠年份
    year = soup.find_all('ul',class_='tagscontent')
    year1 = BeautifulSoup(str(year), 'html.parser')
    year2 = year1.find_all('td')[3]
    car_year = year2.text.strip()
    #外觀顏色
    car_color = []
    color = soup.find_all('ul',class_='tagscontent')
    color1 = BeautifulSoup(str(color), 'html.parser')
    color2 = color1.find_all('td')[7]
    car_color = color2.text.strip()
    #排氣量
    power = soup.find_all('ul',class_='tagscontent') 
    power1 = BeautifulSoup(str(power), 'html.parser')
    power2 = power1.find_all('td')[9]
    car_power = power2.text.strip()
    #變速系統
    speed = soup.find_all('ul',class_='tagscontent')
    speed1 = BeautifulSoup(str(speed), 'html.parser')
    speed2 = speed1.find_all('td')[11]
    car_speed = speed2.text.strip()
    #車門數
    door = soup.find_all('ul',class_='tagscontent')
    door1 = BeautifulSoup(str(door), 'html.parser')
    door2 = year1.find_all('td')[13]
    car_door = door2.text.strip()
    #行駛里程
    km = soup.find_all('ul',class_='tagscontent')
    km1 = BeautifulSoup(str(km), 'html.parser')
    km2 = km1.find_all('td')[15]
    car_km = km2.text.strip()


    tmp = [car_id,car_model,car_price,car_title,car_dealer,car_address,car_year,car_color,car_power,car_speed,car_door,car_km]
    df1.append(tmp)
    df_detail_basic=pd.DataFrame(columns=['id','car_model','car_price','car_title','dealer_name','dealer_address','car_model_year','car_color','car_cylinderVolume','car_gear','car_door','car_mileage'])           
    df = pd.DataFrame(df1 , columns = df_detail_basic.columns)
df

             id         car_model  ... car_door car_mileage
0  101119098695            BMW/寶馬  ...       五門      135711
1  101118814000         Nissan/日產  ...       四門       27178
2  101114848573  Mercedes-Benz/賓士  ...       四門       40000
3  101114200574  Mercedes-Benz/賓士  ...       四門       26000
4  101107039297         Toyota/豐田  ...       四門      230000

[5 rows x 12 columns]

In [48]:
#抓裝備
equipment_columns = ['LED頭燈', 'LED日行燈', 'LED尾燈', 'HID氙氣頭燈', '六安全氣囊以上', '防滑循跡系統', '車道偏移警示', '自動煞車系統' 
                     , '倒車顯影', '天窗', '導航系統', '多媒體影音', '電動座椅', '定速', '恆溫空調', '後座出風口', '免鑰匙啟動', '抬頭顯示器'] 
df2 = pd.DataFrame(columns=equipment_columns)
df3 = pd.DataFrame([list([0]*len(equipment_columns))], columns=equipment_columns)
for url in link_all[:5]:
    #print(url)
    r=requests.get(url,headers=headers)
    soup=BeautifulSoup(r.text,'lxml')     
    equipment = soup.find_all('li', class_='col2')
    if len(equipment) == 2:
        equipment = equipment[1]
    equipment2 = BeautifulSoup(str(equipment), 'html.parser')
    equipment3 = equipment2.find_all('td',class_='last')
    for z in equipment3:
        z = z.text.strip().replace('稅金','').replace('強制險','').replace('過戶','').replace('領牌','').replace('動保設定費','')
        #print(z)
    for i in equipment_columns:
        tmp = []
        if i in z:
            df3[i] = '1'
        else:
            df3[i] = '0'
    df2 = df2.append(df3, ignore_index=True)
df2

  LED頭燈 LED日行燈 LED尾燈 HID氙氣頭燈 六安全氣囊以上 防滑循跡系統  ... 電動座椅 定速 恆溫空調 後座出風口 免鑰匙啟動 抬頭顯示器
0     1      0     1       1       1      1  ...    1  1    1     1     1     1
1     1      0     0       0       0      1  ...    1  0    1     1     1     1
2     1      1     1       1       1      1  ...    1  1    1     1     1     0
3     1      1     1       0       1      1  ...    1  1    1     1     0     0
4     0      0     0       0       1      1  ...    1  1    1     1     1     1

[5 rows x 18 columns]

In [55]:
df4 = pd.concat([df,df2],axis=1)
df4

             id         car_model        car_price  ... 後座出風口 免鑰匙啟動 抬頭顯示器
0  101119098695            BMW/寶馬        838,000 元  ...     1     1     1
1  101118814000         Nissan/日產        389,000 元  ...     1     1     1
2  101114848573  Mercedes-Benz/賓士  8,888,888,888 元  ...     1     1     0
3  101114200574  Mercedes-Benz/賓士               電洽  ...     1     0     0
4  101107039297         Toyota/豐田        150,000 元  ...     1     1     1

[5 rows x 30 columns]

In [ ]:
df.to_csv('Scrape_yahoo_car_url',mode='w',encoding='utf-8')