In [34]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [9]:
df8891column=['car_brand','car_model','car_year','car_mileage','car_price','car_color','car_door','car_seat','car_cylinderVolume','car_driveMode','car_fuel','car_gear','verified','source']

In [10]:
dfHOTcolumns=['car_brand','car_model','car_year','car_mileage','car_price','car_color','car_cylinderVolume','car_driveMode','car_fuel','car_gear','verified','source']

In [11]:
dfSUMcolumns=['car_brand','car_model','car_year','car_mileage','car_price','car_color','car_door','car_seat','car_cylinderVolume','car_driveMode','car_gear','verified','source']

In [12]:
dfisavecolumns=['car_brand','car_model','car_year','car_mileage','car_price','car_color','car_cylinderVolume','car_gear','verified','source']

In [27]:
df_8891 = pd.read_csv('../csv/cleaned_csv/8891_cleaned_20210803.csv', index_col=0)

In [3]:
df_HOT = pd.read_csv('../csv/cleaned_csv/HOT_cleaned_20210803.csv', index_col=0,)

In [4]:
df_SUM = pd.read_csv('../csv/cleaned_csv/SUM_cleaned_20210803.csv', index_col=0)

In [5]:
df_isave = pd.read_csv('../csv/cleaned_csv/car_isave_cleaned_20210803.csv', index_col=0)

In [6]:
df_abc = pd.read_csv('../csv/cleaned_csv/abc_car_cleaned_20210803.csv',index_col=0)

In [7]:
df_usedcar = pd.read_csv('../csv/cleaned_csv/usedcar_clear_0803.csv', index_col=0)

In [8]:
df_ucar = pd.read_csv('../csv/cleaned_csv/ucar_clean_final_0804.csv', index_col=0)

In [10]:
df_yahoo = pd.read_csv('../csv/cleaned_csv/yahoo_clear0804.csv', index_col=0, encoding='utf-8')

In [87]:
df_8891

,id,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_door,car_seat,car_cylinderVolume,car_driveMode,car_fuel,car_gear,verified,car_address,car_title,car_photo,dealer_name,seller_role,dealer_address,sunroof,TPMS,SRS,keyless,theft_alarm,central_lock,ESP,TCS,ABS,cruise_sys,LED_head,isofix,auto_AC,navi_sys,IVI_sys,SW_button,leather_seat,parking_radar,parking_camera,source
0,2802845,HONDA,CIVIC,2013,96000,360000,灰,4,5,1800,2,汽油,自排,0.0,桃園市,✔️0元交車✔️全額貸✔️超貸✔️雙證件核貸✔️強力過件,https://p1.8891.com.tw/2021/06/27/162476870402...,瑞克人氣車庫,瑞克人氣車庫,桃園市中壢區,1,1,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,8891
1,2785082,HONDA,FIT,2018,20000,430000,白,5,5,1500,2,汽油,自排,0.0,桃園市,全車系全額貸款貸款利率優惠中/月付超低/信用小白/瑕疵強力過件,https://p2.8891.com.tw/2021/06/07/162304682321...,阿書強打桃園中古車,阿書強打桃園中古車,桃園市中壢區新中北路819-8號,0,0,1,0,0,1,0,0,0,1,1,0,1,0,0,1,1,1,0,8891
2,2792998,MERCEDES-BENZ,A-CLASS,2020,1000,1830000,白,5,5,2000,4,汽油,手自排,0.0,桃園市,BENZ 正20 A250 AMG 夜色套件 天窗 雙液晶螢幕 桃園弘達,https://p2.8891.com.tw/2021/06/17/162391179429...,弘達國際桃園店,弘達國際桃園店,桃園市桃園區文中路491號,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,1,8891
3,2803991,MERCEDES-BENZ,E-CLASS ESTATE,2018,56000,2380000,黑,5,5,2000,4,汽油,手自排,0.0,桃園市,Benz E400 T P20跟車系統 多光束頭燈 抬頭顯示器 360環景,https://p1.8891.com.tw/2021/06/28/162486901090...,弘達國際桃園店,弘達國際桃園店,桃園市桃園區文中路491號,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,8891
4,2791379,MERCEDES-BENZ,GLC,2016,95000,1530000,白,5,5,2000,4,汽油,手自排,0.0,桃園市,Benz GLC300 AMG LED頭燈 自動停車系統 全景天窗,https://p2.8891.com.tw/2021/06/15/162375801471...,弘達國際桃園店,弘達國際桃園店,桃園市桃園區文中路491號,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,8891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39420,2808626,HONDA,CIVIC,2007,280000,168000,灰,4,5,2000,2,汽油,自手排,0.0,桃園市,稀有2.0一手車/原鈑件/認證車/實車實價,https://p1.8891.com.tw/2021/07/02/7/1625229870...,林先生,車商賣家,NaN,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,8891
39421,2808592,TOYOTA,SIENTA,2018,30000,398000,黑,5,7,1800,2,汽油,手自排,0.0,台中市,撿便宜看過來～限時優惠僅此一週！7人座,https://p1.8891.com.tw/2021/07/02/162522735105...,利先生,車商賣家,NaN,0,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,8891
39422,2808589,MERCEDES-BENZ,E-CLASS SEDAN,2012,184000,720000,黑,5,5,3000,2,汽油,手自排,0.0,高雄市,自售 總代理 W212 E300 Avantgarde,https://p1.8891.com.tw/2021/07/02/162522736284...,黃先生,個人賣家,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,8891
39423,2808577,LUXGEN,S3,2019,23000,260000,白,4,5,1600,2,汽油,自排,0.0,高雄市,家人出國自售 極新,https://p2.8891.com.tw/2021/07/02/162522664574...,黃先生,個人賣家,NaN,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,8891
39424,2808462,BMW,M3,2013,60000,1880000,白,2,4,4000,2,汽油,手自排,0.0,新竹縣,末代 E92 M3 總代理 ,https://p1.8891.com.tw/2021/07/02/162522227859...,姚先生,代理人賣家,NaN,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,8891

In [89]:
df_SUM

,id,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_door,car_seat,car_driveMode,car_fuel,car_gear,verified,car_address,car_title,dealer_name,dealer_address,sunroof,TPMS,SRS,keyless,theft_alarm,central_lock,ESP,TCS,ABS,cruise_sys,HID_head,LED_head,isofix,electric_seat,auto_AC,navi_sys,IVI_sys,SW_button,leather_seat,parking_radar,parking_camera,BSM,ACC,LDW,source,car_cylinderVolume
0,576310,TOYOTA,YARIS,2009,228000,198000,灰,5,5,2,汽油,自排,1,臺中市,【我才最便宜】超便宜認證車 只有永貿免20萬 代步首選 省油妥善率高 車內外漂亮無異味 賞車...,永貿汽車,臺中市潭子區崇德路四段273號(https://goo.gl/maps/GyN2YDTo5en),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SUM,1500
1,576301,TOYOTA,YARIS,2017,35000,398000,白,5,5,2,汽油,手自排,1,臺中市,【全台最便宜不用再看了】僅跑3萬 一手原版件認證車 盲點偵測 大螢幕影音 黑橘雙色椅 黑頂棚...,永貿汽車,臺中市潭子區崇德路四段273號(https://goo.gl/maps/GyN2YDTo5en),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SUM,1500
2,576272,HONDA,HR-V,2017,81359,568000,藍,5,5,2,汽油,手自排,1,臺中市,正2017年 HRV 倒車顯影 換檔撥片 恆溫 IKEY 摸門解鎖 定速 多功能方向盤 Ec...,永貿汽車,臺中市潭子區崇德路四段273號(https://goo.gl/maps/GyN2YDTo5en),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SUM,1800
3,576264,TOYOTA,VIOS,2016,49345,338000,白,4,5,2,汽油,手自排,1,臺中市,【特價】僅跑4萬9 原版件認證車 車況與車內氣氛超好 皮椅如新 等您來鑑定 賞車下定送大螢幕...,永貿汽車,臺中市潭子區崇德路四段273號(https://goo.gl/maps/GyN2YDTo5en),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SUM,1500
4,576220,HYUNDAI,GRAND STAREX,2016,116784,788000,銀,5,9,2,柴油,手自排,1,臺中市,【特價】正2016年 半滑軌 一手少跑認證車 新車膜都還沒撕掉! 超漂亮! 全台最大的TQ批...,永貿汽車,臺中市潭子區崇德路四段273號(https://goo.gl/maps/GyN2YDTo5en),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SUM,2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10141,420922,NISSAN,TIIDA 5D,2006,126768,198000,棕,5,5,2,汽油,自排,1,彰化縣,IKEY DVD【僑將汽車】全額貸 保證實車 有誠皆可議,僑將汽車,彰化縣福興鄉彰鹿路六段286號,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,SUM,1800
10142,408838,VW,GOLF VI,2012,90000,368000,銀,5,5,2,汽油,自手排,1,新北市,SUM 金鑽店“★0利率送鍍膜☆頂級渦輪1.4TSI•11安～自用車庫車•選配大螢幕•恆溫+...,金豪華汽車,新北市三重區重陽路三段2號(中山高速公路下直走第六個紅綠燈口，捷運為三重菜寮站，【SUM連續...,0,1,1,0,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,1,1,0,0,0,SUM,1400
10143,401609,AUDI,A3 SEDAN,2015,90000,668000,白,4,5,2,汽油,自手排,1,新北市,SUM 金鑽店〞☆0利率送鍍膜★奧迪 A3 1.4T小改款總代理‧跑車座椅‧一手車保證只跑9...,金豪華汽車,新北市三重區重陽路三段2號(中山高速公路下直走第六個紅綠燈口，捷運為三重菜寮站，【SUM連續...,0,0,1,0,1,1,0,1,1,1,1,0,1,0,1,0,0,1,1,0,0,0,0,0,SUM,1400
10144,334558,HONDA,CIVIC,2007,144150,288000,黑,4,5,2,汽油,自排,1,臺中市,1.8 EX黑.天窗.ABS.雙氣囊.整台原漆.真是美!,中古車站汽車,臺中市南屯區永春路35-9號(--- 中彰快速道路 *永春路出口*-永春路左轉方向30秒即達...,1,0,1,0,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,SUM,1800
10145,241453,MITSUBISHI,NEW SAVRIN,2005,120742,178000,黑灰雙,5,6,2,汽油,手自排,1,臺中市,2.0 六人頂級款 -新車價91.9萬.美!,中古車站汽車,臺中市南屯區永春路35-9號(--- 中彰快速道路 *永春路出口*-永春路左轉方向30秒即達...,1,0,1,0,1,1,0,0,1,0,1,0,0,1,1,0,1,1,1,1,1,0,0,0,SUM,2000

In [88]:
df_HOT

,id,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_cylinderVolume,car_driveMode,car_fuel,car_gear,verified,car_address,car_title,car_photo,dealer_name,dealer_address,sunroof,TPMS,SRS,keyless,ESP,ABS,cruise_sys,HID_head,isofix,electric_seat,auto_AC,navi_sys,IVI_sys,leather_seat,parking_radar,parking_camera,BSM,LDW,source
0,236581,TOYOTA,ALTIS,2009,197710,196000,黑,1800,2.0,汽油,手自排,1,高雄市,豐田ALTIS 1800cc 2009年 黑色0頭款可全貸,https://www.hotcar.com.tw/UPLOAD/CW/HF1002/260...,上暘汽車,高雄市鳥松區神農路856號,0,0,1,0,0,1,1,0,0,0,1,0,0,1,1,0,0,0,HOT
1,236578,MITSUBISHI,DELICA,2016,81609,358000,深藍,2400,2.0,汽油,手排,1,高雄市,三菱得利卡2400cc 2016年框式附加吊桿0頭款可全貸,https://www.hotcar.com.tw/UPLOAD/CW/HF1002/260...,上暘汽車,高雄市鳥松區神農路856號,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,HOT
2,236571,SUZUKI,CARRY,2013,53167,286000,銀,1600,2.0,汽油,手排,1,高雄市,鈴木吉利 1590cc 2013年銀色0頭款可全貸,https://www.hotcar.com.tw/UPLOAD/CW/HF1002/260...,上暘汽車,高雄市鳥松區神農路856號,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,HOT
3,236495,NISSAN,MARCH,2013,92757,238000,淺綠,1500,2.0,汽油,自排,1,台中市,新手駕駛首選 顯眼 小台 好停車 好照顧,https://www.hotcar.com.tw/UPLOAD/CW/HD1076/260...,聖傑汽車(烏日店),台中市烏日區中山路三段903號,0,0,0,0,0,1,0,0,0,0,0,1,1,1,1,1,0,0,HOT
4,236493,NISSAN,SENTRA,2015,43307,378000,白,1800,2.0,汽油,手自排,1,台中市,Aero 旗艦版 電動座椅調整 4安 多合一影音,https://www.hotcar.com.tw/UPLOAD/CW/HD1076/260...,聖傑汽車(烏日店),台中市烏日區中山路三段903號,0,0,1,1,0,1,1,0,0,1,1,1,1,1,1,1,0,0,HOT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6262,187472,MITSUBISHI,VERYCA,2012,169338,288000,深藍,1200,4.0,汽油,手排,0,嘉義市,"車況優,無改裝,操控佳,省油",https://www.hotcar.com.tw/UPLOAD/CW/HE2002/198...,龍順汽車,嘉義市西區世賢路二段229號,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,HOT
6263,180860,MAZDA,MAZDA 5,2007,100000,298000,淺藍,2000,2.0,汽油,手自排,0,桃園市,忠泰汽車 實車實價 2007 MAZDA 5 七人座 天窗版,https://www.hotcar.com.tw/UPLOAD/CW/HC1089/194...,忠泰汽車,桃園市桃園區經國路461號,1,0,1,0,0,1,0,0,0,1,1,0,1,1,1,0,0,0,HOT
6264,175198,BMW,530,2004,146516,468000,黑,3000,2.0,汽油,手自排,0,彰化縣,"少開,車況優,馬力強,操控佳,空間大",https://www.hotcar.com.tw/UPLOAD/CW/HD2031/184...,竣富汽車,彰化縣和美鎮線東路二段520號,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,0,0,0,HOT
6265,173304,MITSUBISHI,GRUNDER,2005,162257,148000,銀,2400,2.0,汽油,手自排,0,彰化縣,"家庭用車,馬力強,空間大,操控佳,車況優",https://www.hotcar.com.tw/UPLOAD/CW/HD2031/182...,竣富汽車,彰化縣和美鎮線東路二段520號,1,0,1,0,0,1,0,0,0,1,1,0,1,1,1,1,0,0,HOT
6266,156514,VOLKSWAGEN,GOLF,2004,218426,168000,銀,1600,2.0,汽油,手自排,0,桃園市,忠泰汽車 2004 VW GOLF VI GLORY MK4 1.6 精裝版天窗,https://www.hotcar.com.tw/UPLOAD/CW/HC1089/253...,忠泰汽車,桃園市桃園區經國路461號,1,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,HOT

In [52]:
df_SUM['car_cylinderVolume'] = df_SUM['car_cylinderVolumn']
del df_SUM['car_cylinderVolumn']

In [21]:
df_isave['source'] = 'isave'

In [19]:
df_abc['source'] = 'abc'

In [16]:
df_usedcar['source'] = 'usedcar'

In [13]:
df_ucar

,id,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_cylinderVolume,car_fuel,car_gear,...,navi_sys,sunroof,IVI_sys,HID_head,auto_AC,keyless,SRS,parking_radar,car_driveMode,source
1,b58f4aa2cc5744b1b71012991ea7c338,MERCEDES-BENZ,E-CLASS,2000,86000,498000,白,5400,汽 油,手 自 排,...,0,1,0,0,1,0,1,1,2,U-car
2,0a86269851dd4b68b6dc156b74c01a6d,SUZUKI,SWIFT,2006,140000,208000,白,1500,汽 油,自 排,...,1,0,1,0,0,1,1,1,2,U-car
3,b88ba4c247e84260a86d183aef86ac1c,BMW,3 SERIES,2005,110039,288000,黑,2500,汽 油,手 自 排,...,0,1,0,1,1,0,1,0,2,U-car
4,60c38a8a372242ffae6c31df3ab822ad,NISSAN,MARCH,2016,0,338000,白,1500,汽 油,自 排,...,1,0,1,0,1,1,1,1,2,U-car
5,f1b79c9951784bd195ea4a4c50a3dd70,FORD,FOCUS,2006,144444,330000,藍,2500,汽 油,手 排,...,0,1,0,0,0,0,1,1,2,U-car
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3256,dbe36ce740074ff59a72f55c743a81dd,NISSAN,X-TRAIL,2004,100000,118000,棕,2500,汽 油,自 排,...,1,1,1,1,1,0,1,1,2,U-car
3257,712d10fd290641319e5df58150f98f4a,SAAB,9000,1996,210000,120000,黑,2300,汽 油,自 排,...,0,0,0,0,0,0,0,0,2,U-car
3259,8f907e7f65fd4318b1d2f95acb4eaf74,MITSUBISHI,COLT PLUS,2010,112849,218000,其他,1600,汽 油,自 排,...,1,0,0,0,0,0,1,1,2,U-car
3261,2b2bbb91463442b48cf2fbadfe5e1349,SUBARU,LEGACY,2011,159140,380000,白,2500,汽 油,手 自 排,...,1,0,1,1,1,0,1,1,2,U-car
3262,ccddb925e57f47d99ddefce734c0c16a,HONDA,CRV,2015,100343,588000,白,2000,汽 油,自 排,...,1,0,0,1,1,0,1,1,2,U-car

In [51]:
df_yahoo

,id,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_door,car_cylinderVolume,car_fuel,car_gear,car_address,car_title,car_photo,dealer_name,dealer_address,SRS,TCS,cruise_sys,LED_head,electric_seat,auto_AC,navi_sys,IVI_sys,parking_camera,LDW,source,HID_head,sunroof,keyless
1,101100512019,MERCEDESBENZ,GLCCLASS,2020,21000,"2,388,000",白,4,2200,汽油,手自排,台北市,2021 Benz GLC300 AMG 白色 柏林 全景 環景 - 名帥汽車,https://ct.yimg.com/xd/api/res/1.2/twGtqbwA.6K...,['名帥優質車'],台北市中山區民族東路67號,1,1,1,1,1,1,1,1,1,1,yahoo,0,1,1
2,101118624358,MERCEDESBENZ,GCLASS,2011,150000,"2,380,000",銀,5,4800,汽油,自排,台北市,馳堂 2011 G500 總代理 原鈑件 AMG BRABUS 精品加持,https://ct.yimg.com/xd/api/res/1.2/TBiTUleJOss...,['馳堂車業'],台北市士林區延平北路七段141號,1,1,1,1,1,1,1,1,1,1,yahoo,0,1,1
3,101115566834,TOYOTA,ALPHARD,2018,68000,"2,380,000",白,5,3300,汽油,手自排,桃園市,美好關係 19年式Toyota Alphard總代理小改款 原廠保養 後座影音,https://ct.yimg.com/xd/api/res/1.2/LueKsetrekU...,['美好關係 勁德汽車'],桃園市桃園區經國路32號,1,1,1,1,0,1,1,0,1,0,yahoo,0,1,1
4,101113581267,MERCEDESBENZ,GLCCLASS,2017,66000,"2,380,000",黑,5,2600,汽油,手自排,新北市,豐駿樹林北大國際店-23P.環景. AMG GLC 43 Coupe黑#9768,https://ct.yimg.com/xd/api/res/1.2/O66LOhS7maA...,['豐駿汽車樹林北大國際店'],新北市樹林區佳園路二段52號,1,1,1,1,1,1,0,1,1,1,yahoo,0,1,1
5,101105075788,MERCEDESBENZ,GCLASS,2010,190000,"2,380,000",黑,5,4800,汽油,手自排,彰化縣,2010年 BENZ G500 總代理 保證實車實價,https://ct.yimg.com/xd/api/res/1.2/tQLeHcpCjCV...,['銓鎰汽車有限公司SAVE認證'],彰化縣埔心鄉中正路一段555之17號,1,1,1,0,1,1,0,0,0,0,yahoo,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,101124711340,VOLVO,C30,2011,74569,"250,000",銀,3,2200,汽油,手自排,新北市,A自售 2011年 VOLVO C30 2.0L,https://ct.yimg.com/xd/api/res/1.2/68y95jl4xnJ...,['Y5038709999'],新北市五股區新城一路,1,1,1,0,1,1,0,1,0,0,yahoo,0,1,1
746,101123612053,SMART,FORTWO,2015,50000,"250,000",白,3,1200,汽油,手自排,彰化縣,2015年 SMART 5萬公里 原鈑件 精選車況 市區超好停,https://ct.yimg.com/xd/api/res/1.2/cTkvsflnawb...,['Y1632399519'],彰化縣員林鎮至善街33號,1,1,1,0,1,1,0,1,0,0,yahoo,0,1,1
747,101122338352,LEXUS,IS,2009,107508,"250,000",銀,4,2600,汽油,手自排,新北市,疫情振興專案 原廠保養 凌志 IS250 2009年 認證優質好車,https://ct.yimg.com/xd/api/res/1.2/ImixFqPKS3c...,['Y6785103599'],新北市汐止區康寧街附近,1,1,1,0,1,1,1,1,1,0,yahoo,0,1,1
748,101120157122,SKODA,FABIA,2009,270668,"250,000",紅,5,1200,汽油,手自排,彰化縣,2009 Skoda Fabia 一手車 省稅金 好保養,https://ct.yimg.com/xd/api/res/1.2/lAurFTLJStq...,['Y0821500583'],彰化縣鹿港鎮中正路306號,1,1,1,0,1,1,1,1,1,0,yahoo,0,1,1
749,101120131242,BMW,3SERIESSEDAN,2014,66487,"250,000",灰,4,2200,汽油,手自排,新北市,[歐德義國際] 2014年 BMW 320 貴婦買菜車託售,https://ct.yimg.com/xd/api/res/1.2/1lVn_EC9Xu1...,['Y0920017720'],新北市五股區新城一路60號(和運租車對面),1,1,1,0,1,1,1,1,1,0,yahoo,1,1,1

In [48]:
df_yahoo['keyless'] = df_yahoo['Keyless']
del df_yahoo['Keyless']

In [46]:
df_yahoo['sunroof'] = df_yahoo['Sunroof']

In [47]:
del df_yahoo['Sunroof']

In [14]:
df_yahoo['source'] = 'yahoo'

In [34]:
df_usedcar['car_driveMode'] = df_usedcar['car_driveMode'].str.replace('WD','')

df_usedcar['car_driveMode'] = df_usedcar['car_driveMode'].astype(int)

df_usedcar['car_color'] = df_usedcar['car_color'].str.replace('色','')
df_usedcar['car_fuel'] = df_usedcar['car_fuel'].str.replace('車','')

In [28]:
df_usedcar.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2485 entries, 0 to 2484
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   car_brand           2485 non-null   object
 1   car_model           2485 non-null   object
 2   car_year            2485 non-null   int64
 3   car_mileage         2485 non-null   int64
 4   car_price           2485 non-null   int64
 5   car_color           2485 non-null   object
 6   car_door            2462 non-null   float64
 7   car_seat            2465 non-null   float64
 8   car_cylinderVolume  2485 non-null   int64
 9   car_driveMode       2485 non-null   int64
 10  car_fuel            2485 non-null   object
 11  car_gear            2485 non-null   object
 12  source              2485 non-null   object
dtypes: float64(2), int64(5), object(6)
memory usage: 271.8+ KB

In [57]:
df_8891

,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_door,car_seat,car_cylinderVolume,car_driveMode,car_fuel,car_gear,verified,source
0,HONDA,CIVIC,2013,96000,360000,灰,4,5,1800,2,汽油,自排,0.0,8891
1,HONDA,FIT,2018,20000,430000,白,5,5,1500,2,汽油,自排,0.0,8891
2,MERCEDES-BENZ,A-CLASS,2020,1000,1830000,白,5,5,2000,4,汽油,手自排,0.0,8891
3,MERCEDES-BENZ,E-CLASS ESTATE,2018,56000,2380000,黑,5,5,2000,4,汽油,手自排,0.0,8891
4,MERCEDES-BENZ,GLC,2016,95000,1530000,白,5,5,2000,4,汽油,手自排,0.0,8891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39420,HONDA,CIVIC,2007,280000,168000,灰,4,5,2000,2,汽油,自手排,0.0,8891
39421,TOYOTA,SIENTA,2018,30000,398000,黑,5,7,1800,2,汽油,手自排,0.0,8891
39422,MERCEDES-BENZ,E-CLASS SEDAN,2012,184000,720000,黑,5,5,3000,2,汽油,手自排,0.0,8891
39423,LUXGEN,S3,2019,23000,260000,白,4,5,1600,2,汽油,自排,0.0,8891
39424,BMW,M3,2013,60000,1880000,白,2,4,4000,2,汽油,手自排,0.0,8891

In [56]:
df_SUM

,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_door,car_seat,car_cylinderVolume,car_driveMode,car_gear,verified,source
0,TOYOTA,YARIS,2009,228000.0,198000,灰,5,5,1500,2,自排,1.0,SUM
1,TOYOTA,YARIS,2017,35000.0,398000,白,5,5,1500,2,手自排,1.0,SUM
2,HONDA,HR-V,2017,81359.0,568000,藍,5,5,1800,2,手自排,1.0,SUM
3,TOYOTA,VIOS,2016,49345.0,338000,白,4,5,1500,2,手自排,1.0,SUM
4,HYUNDAI,GRAND STAREX,2016,116784.0,788000,銀,5,9,2500,2,手自排,1.0,SUM
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10141,NISSAN,TIIDA 5D,2006,126768.0,198000,棕,5,5,1800,2,自排,1.0,SUM
10142,VW,GOLF VI,2012,90000.0,368000,銀,5,5,1400,2,自手排,1.0,SUM
10143,AUDI,A3 SEDAN,2015,90000.0,668000,白,4,5,1400,2,自手排,1.0,SUM
10144,HONDA,CIVIC,2007,144150.0,288000,黑,4,5,1800,2,自排,1.0,SUM
10145,MITSUBISHI,NEW SAVRIN,2005,120742.0,178000,黑灰雙,5,6,2000,2,手自排,1.0,SUM

In [44]:
df_8891['car_model']= df_8891['car_model'].str.upper()

In [55]:
df_HOT

,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_cylinderVolume,car_driveMode,car_fuel,car_gear,verified,source
0,TOYOTA,ALTIS,2009,197710,196000,黑,1800,2,汽油,手自排,1,HOT
1,MITSUBISHI,DELICA,2016,81609,358000,深藍,2400,2,汽油,手排,1,HOT
2,SUZUKI,CARRY,2013,53167,286000,銀,1600,2,汽油,手排,1,HOT
3,NISSAN,MARCH,2013,92757,238000,淺綠,1500,2,汽油,自排,1,HOT
4,NISSAN,SENTRA,2015,43307,378000,白,1800,2,汽油,手自排,1,HOT
...,...,...,...,...,...,...,...,...,...,...,...,...
6262,MITSUBISHI,VERYCA,2012,169338,288000,深藍,1200,4,汽油,手排,0,HOT
6263,MAZDA,MAZDA 5,2007,100000,298000,淺藍,2000,2,汽油,手自排,0,HOT
6264,BMW,530,2004,146516,468000,黑,3000,2,汽油,手自排,0,HOT
6265,MITSUBISHI,GRUNDER,2005,162257,148000,銀,2400,2,汽油,手自排,0,HOT
6266,VOLKSWAGEN,GOLF,2004,218426,168000,銀,1600,2,汽油,手自排,0,HOT

In [54]:
df_SUM

,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_door,car_seat,car_cylinderVolume,car_driveMode,car_gear,verified,source
0,TOYOTA,YARIS,2009,228000.0,198000,灰,5,5,1500,2,自排,1.0,SUM
1,TOYOTA,YARIS,2017,35000.0,398000,白,5,5,1500,2,手自排,1.0,SUM
2,HONDA,HR-V,2017,81359.0,568000,藍,5,5,1800,2,手自排,1.0,SUM
3,TOYOTA,VIOS,2016,49345.0,338000,白,4,5,1500,2,手自排,1.0,SUM
4,HYUNDAI,GRAND STAREX,2016,116784.0,788000,銀,5,9,2500,2,手自排,1.0,SUM
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10141,NISSAN,TIIDA 5D,2006,126768.0,198000,棕,5,5,1800,2,自排,1.0,SUM
10142,VW,GOLF VI,2012,90000.0,368000,銀,5,5,1400,2,自手排,1.0,SUM
10143,AUDI,A3 SEDAN,2015,90000.0,668000,白,4,5,1400,2,自手排,1.0,SUM
10144,HONDA,CIVIC,2007,144150.0,288000,黑,4,5,1800,2,自排,1.0,SUM
10145,MITSUBISHI,NEW SAVRIN,2005,120742.0,178000,黑灰雙,5,6,2000,2,手自排,1.0,SUM

In [53]:
df_isave

,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_cylinderVolume,car_gear,verified,source
0,LUXGEN,URX,2021.0,1.0,980000.0,白,1798.0,手自排,1.0,ISAVE
1,LUXGEN,URX,2021.0,1.0,980000.0,白,1798.0,手自排,1.0,ISAVE
2,FORD,KUGA,2021.0,4275.0,1090000.0,白,1999.0,手自排,1.0,ISAVE
4,TOYOTA,COROLLA CROSS,2021.0,3.0,728000.0,白,1798.0,手自排,1.0,ISAVE
10,HONDA,TYPE R,2021.0,112.0,2280000.0,白,1996.0,手排,0.0,ISAVE
...,...,...,...,...,...,...,...,...,...,...
1671,TOYOTA,PREMIO,1998.0,220000.0,188000.0,銀,1998.0,自排,0.0,ISAVE
1672,MITSUBISHI,PAJERO,1998.0,230446.0,97000.0,藍,2972.0,自排,0.0,ISAVE
1673,MITSUBISHI,VARICA,1998.0,165686.0,978000.0,紅,1094.0,手排,0.0,ISAVE
1682,TOYOTA,CAMRY,1997.0,130000.0,198000.0,綠,2995.0,自排,0.0,ISAVE
1684,TOYOTA,TERCEL,1997.0,132090.0,158000.0,白,1497.0,自排,0.0,ISAVE

In [15]:
df_isave.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4128 entries, 0 to 1684
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   car_brand    4049 non-null   object
 1   car_model    4049 non-null   object
 2   car_year     4049 non-null   float64
 3   car_mileage  1937 non-null   float64
 4   car_price    4128 non-null   float64
 5   source       4128 non-null   object
dtypes: float64(3), object(3)
memory usage: 225.8+ KB

In [21]:
df_isave.dropna(axis=0, inplace=True)

In [42]:
df_isave['car_year'] = df_isave['car_year'].astype(int)
df_isave['car_mileage'] = df_isave['car_mileage'].astype(int)
df_isave['car_price'] = df_isave['car_mileage'].astype(int)

In [44]:
df_abc

,id,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_door,car_seat,car_cylinderVolume,car_driveMode,car_fuel,car_gear,verified,car_address,car_title,car_photo,dealer_name,seller_role,dealer_address,sunroof,TPMS,SRS,keyless,theft_alarm,central_lock,ESP,TCS,ABS,cruise_sys,HID_head,LED_head,isofix,electric_seat,auto_AC,IVI_sys,SW_button,leather_seat,parking_radar,parking_camera,BSM,ACC,LDW,source
0,1566744,TOYOTA,RAV4 2.0 E (4代),2017,81691,718000,NaN,NaN,5.0,2.000000e+09,2.0,汽油,CVT 無段變速,1,南投縣,TOYOTA RAV4 2.0 E (4代)2017,https://img.abccar.com.tw/resize?key=650x435/h...,TOYOTA認證中古車/中誠草屯所,NaN,賞車地址：南投縣草屯鎮太平路一段9號,0,1,1,1,NaN,NaN,NaN,1,1,0,NaN,NaN,NaN,1,0,0,0,1,NaN,1,0,NaN,1,abc
1,1567986,TOYOTA,COROLLA ALTIS 1.8 雅緻版 (11代),2013,100515,388000,NaN,NaN,5.0,1.800000e+09,2.0,汽油,手自排,1,雲林縣,TOYOTA Corolla Altis 1.8 雅緻版 (11代)2013,https://img.abccar.com.tw/resize?key=650x435/h...,TOYOTA認證中古車/南都斗六所,NaN,賞車地址：雲林縣斗六市明德北路三段280號,0,0,1,0,NaN,NaN,NaN,0,1,0,NaN,NaN,NaN,0,0,1,0,1,NaN,1,0,NaN,0,abc
2,1550919,TOYOTA,YARIS 1.5 E (2代),2013,127095,328000,NaN,NaN,5.0,1.500000e+09,2.0,汽油,自排,1,彰化縣,TOYOTA Yaris 1.5 E (2代)2013,https://img.abccar.com.tw/resize?key=650x435/h...,TOYOTA認證中古車/中誠彰化所,NaN,賞車地址：彰化縣花壇鄉中山路一段93-1號,0,0,1,0,NaN,NaN,NaN,0,1,0,NaN,NaN,NaN,0,0,1,0,1,NaN,0,0,NaN,0,abc
3,1568145,LEXUS,RX350 頂級版 (3代),2015,53004,1168000,紅,NaN,5.0,3.500000e+09,4.0,汽油,手自排,0,新北市,LEXUS RX350 頂級版 (3代)2015,https://img.abccar.com.tw/resize?key=650x435/h...,小鍾,NaN,賞車地址：新北市樹林區中正路421號,1,1,1,1,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,1,1,1,1,1,NaN,1,1,NaN,1,abc
4,1531069,LUXGEN,7 MPV 精緻型 8人座,2012,250000,238000,白,NaN,8.0,2.200000e+09,2.0,汽油,手自排,0,新北市,LUXGEN 7 MPV 精緻型 8人座2012,https://img.abccar.com.tw/resize?key=650x435/h...,宋小姐,NaN,賞車地址：新北市樹林區大安路558號,0,0,1,1,NaN,NaN,NaN,0,1,0,NaN,NaN,NaN,0,1,0,0,1,NaN,1,0,NaN,0,abc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27277,1496545,SUBARU,IMPREZA 5D 1.6I-S (5代),2017,66000,698000,白,NaN,5.0,1.600000e+09,4.0,汽油,CVT 無段變速,0,新北市,SUBARU Impreza 5D 1.6i-S (5代)2017,https://img.abccar.com.tw/resize?key=650x435/h...,郭麟政,NaN,賞車地址：新北市板橋區文化路一段201-1號,1,1,0,1,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,1,1,1,1,1,NaN,1,1,NaN,0,abc
27278,1531472,LEXUS,RX330 (2代),2003,16,110000,棕,NaN,5.0,3.300000e+09,4.0,汽油,手自排,0,新北市,LEXUS RX330 (2代)2003,https://img.abccar.com.tw/resize?key=650x435/h...,蔡先生,NaN,賞車地址：新北市樹林區新北市樹林區樹新路107號,0,0,0,0,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,0,0,0,0,0,NaN,0,0,NaN,0,abc
27279,1565354,MAZDA,3 5D,2017,11117,350000,白,NaN,5.0,2.000000e+09,2.0,汽油,手自排,0,新北市,Mazda 3 5D2017,https://img.abccar.com.tw/resize?key=650x435/h...,何小姐,NaN,賞車地址：新北市五股區成泰路三段,0,0,1,1,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,1,1,1,1,1,NaN,1,0,NaN,0,abc
27280,1528081,SUZUKI,SWIFT 1.2 GLX,2015,50000,370000,藍,NaN,5.0,1.200000e+09,2.0,汽油,自排,0,新北市,SUZUKI Swift 1.2 GLX2015,https://img.abccar.com.tw/resize?key=650x435/h...,戴楷文,NaN,賞車地址：新北市蘆洲區三民路86-2號,0,1,1,1,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,0,1,1,1,1,NaN,1,0,NaN,0,abc
27281,1539171,PORSCHE,CAYENNE DIESEL (MK2),2014,90000,1680000,白,NaN,5.0,3.000000e+09,4.0,柴油,手自排,0,新北市,Porsche Cayenne Diesel (Mk2)2014,https://img.abccar.com.tw/resize?key=650x435/h...,值班人員,NaN,賞車地址：新北市林口區文化北路二段198號,0,1,0,0,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,1,1,1,1,1,NaN,0,0,NaN,0,abc

In [41]:
df_abc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27282 entries, 0 to 4614
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   car_brand    27282 non-null  object
 1   car_model    27282 non-null  object
 2   car_year     27282 non-null  int64
 3   car_mileage  27282 non-null  int64
 4   car_price    27282 non-null  int64
 5   source       27282 non-null  object
dtypes: int64(3), object(3)
memory usage: 2.0+ MB

In [34]:
df_abc = df_abc.replace({'car_mileage':','}, {'car_mileage':''}, regex=True)

In [40]:
df_abc['car_mileage'] = df_abc['car_mileage'].astype('int64')
df_abc['car_price'] = df_abc['car_price'].astype('int64')

In [53]:
df_final = pd.concat([df_HOT, df_SUM, df_8891, df_isave, df_abc, df_usedcar, df_ucar,df_yahoo])

In [31]:
df_final = df_final.reset_index(drop=True)

In [36]:
del df_final['seller_role']

In [93]:
df_final

,id,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_cylinderVolume,car_driveMode,car_fuel,car_gear,verified,car_address,car_title,car_photo,dealer_name,dealer_address,sunroof,TPMS,SRS,keyless,ESP,ABS,cruise_sys,HID_head,isofix,electric_seat,auto_AC,navi_sys,IVI_sys,leather_seat,parking_radar,parking_camera,BSM,LDW,source,car_door,car_seat,theft_alarm,central_lock,TCS,LED_head,SW_button,ACC,seller_role
0,236581,TOYOTA,ALTIS,2009.0,197710.0,196000,黑,1800.0,2.0,汽油,手自排,1,高雄市,豐田ALTIS 1800cc 2009年 黑色0頭款可全貸,https://www.hotcar.com.tw/UPLOAD/CW/HF1002/260...,上暘汽車,高雄市鳥松區神農路856號,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,HOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,236578,MITSUBISHI,DELICA,2016.0,81609.0,358000,深藍,2400.0,2.0,汽油,手排,1,高雄市,三菱得利卡2400cc 2016年框式附加吊桿0頭款可全貸,https://www.hotcar.com.tw/UPLOAD/CW/HF1002/260...,上暘汽車,高雄市鳥松區神農路856號,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,HOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,236571,SUZUKI,CARRY,2013.0,53167.0,286000,銀,1600.0,2.0,汽油,手排,1,高雄市,鈴木吉利 1590cc 2013年銀色0頭款可全貸,https://www.hotcar.com.tw/UPLOAD/CW/HF1002/260...,上暘汽車,高雄市鳥松區神農路856號,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,HOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,236495,NISSAN,MARCH,2013.0,92757.0,238000,淺綠,1500.0,2.0,汽油,自排,1,台中市,新手駕駛首選 顯眼 小台 好停車 好照顧,https://www.hotcar.com.tw/UPLOAD/CW/HD1076/260...,聖傑汽車(烏日店),台中市烏日區中山路三段903號,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,HOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,236493,NISSAN,SENTRA,2015.0,43307.0,378000,白,1800.0,2.0,汽油,手自排,1,台中市,Aero 旗艦版 電動座椅調整 4安 多合一影音,https://www.hotcar.com.tw/UPLOAD/CW/HD1076/260...,聖傑汽車(烏日店),台中市烏日區中山路三段903號,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,HOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,101124711340,VOLVO,C30,2011.0,74569.0,"250,000",銀,2200.0,NaN,汽油,手自排,NaN,新北市,A自售 2011年 VOLVO C30 2.0L,https://ct.yimg.com/xd/api/res/1.2/68y95jl4xnJ...,['Y5038709999'],新北市五股區新城一路,1.0,NaN,1.0,1.0,NaN,NaN,1.0,0.0,NaN,1.0,1.0,0.0,1.0,NaN,NaN,0.0,NaN,0.0,yahoo,3.0,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN
746,101123612053,SMART,FORTWO,2015.0,50000.0,"250,000",白,1200.0,NaN,汽油,手自排,NaN,彰化縣,2015年 SMART 5萬公里 原鈑件 精選車況 市區超好停,https://ct.yimg.com/xd/api/res/1.2/cTkvsflnawb...,['Y1632399519'],彰化縣員林鎮至善街33號,1.0,NaN,1.0,1.0,NaN,NaN,1.0,0.0,NaN,1.0,1.0,0.0,1.0,NaN,NaN,0.0,NaN,0.0,yahoo,3.0,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN
747,101122338352,LEXUS,IS,2009.0,107508.0,"250,000",銀,2600.0,NaN,汽油,手自排,NaN,新北市,疫情振興專案 原廠保養 凌志 IS250 2009年 認證優質好車,https://ct.yimg.com/xd/api/res/1.2/ImixFqPKS3c...,['Y6785103599'],新北市汐止區康寧街附近,1.0,NaN,1.0,1.0,NaN,NaN,1.0,0.0,NaN,1.0,1.0,1.0,1.0,NaN,NaN,1.0,NaN,0.0,yahoo,4.0,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN
748,101120157122,SKODA,FABIA,2009.0,270668.0,"250,000",紅,1200.0,NaN,汽油,手自排,NaN,彰化縣,2009 Skoda Fabia 一手車 省稅金 好保養,https://ct.yimg.com/xd/api/res/1.2/lAurFTLJStq...,['Y0821500583'],彰化縣鹿港鎮中正路306號,1.0,NaN,1.0,1.0,NaN,NaN,1.0,0.0,NaN,1.0,1.0,1.0,1.0,NaN,NaN,1.0,NaN,0.0,yahoo,5.0,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN
749,101120131242,BMW,3SERIESSEDAN,2014.0,66487.0,"250,000",灰,2200.0,NaN,汽油,手自排,NaN,新北市,[歐德義國際] 2014年 BMW 320 貴婦買菜車託售,https://ct.yimg.com/xd/api/res/1.2/1lVn_EC9Xu1...,['Y0920017720'],新北市五股區新城一路60號(和運租車對面),1.0,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,1.0,NaN,NaN,1.0,NaN,0.0,yahoo,4.0,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN

In [92]:
df_copy = df_final.copy()

In [ ]:
df_final = df_copy.copy()

In [64]:
df_final['car_gear'].unique()

array(['手自排', '手排', '自排', '自手排', nan], dtype=object)

In [57]:
df_final.loc[df_final['car_gear'].str.contains('CVT') == True, 'car_gear'] = '手自排'

df_final.loc[df_final['car_gear'].str.contains('手 自 排') == True, 'car_gear'] = '手自排'

df_final.loc[df_final['car_gear'].str.contains('自 手 排') == True, 'car_gear'] = '自手排'

df_final.loc[df_final['car_gear'].str.contains('自 排') == True, 'car_gear'] = '自排'

df_final.loc[df_final['car_gear'].str.contains('手 排') == True, 'car_gear'] = '手排'

In [65]:
df_final['car_door'].unique()

array([nan,  5.,  4.,  2.,  3.,  6.,  0.])

In [66]:
df_final['car_seat'].unique()

array([nan,  5.,  9.,  4.,  7.,  8.,  3.,  6.,  2., 12., 10.,  0.])

In [80]:
df_final['car_fuel'].unique()

array(['汽油', nan, '柴油', '油電', '電動', '柴電'], dtype=object)

In [79]:
df_final.loc[df_final['car_fuel'].str.contains('0') == True, 'car_fuel'] = np.NaN

df_final.loc[df_final['car_fuel'].str.contains('5') == True, 'car_fuel'] = '油電'

df_final.loc[df_final['car_fuel'].str.contains('汽 油') == True, 'car_fuel'] = '汽油'

df_final.loc[df_final['car_fuel'].str.contains('柴 油') == True, 'car_fuel'] = '柴油'

df_final.loc[df_final['car_fuel'].str.contains('柴電複合') == True, 'car_fuel'] = '柴電'

df_final.loc[df_final['car_fuel'].str.contains('輕油電柴油') == True, 'car_fuel'] = '柴電'

df_final.loc[df_final['car_fuel'].str.contains('48V輕油電') == True, 'car_fuel'] = '油電'

df_final.loc[df_final['car_fuel'].str.contains('插電式油電') == True, 'car_fuel'] = '油電'

df_final.loc[df_final['car_fuel'].str.contains('油電複合') == True, 'car_fuel'] = '油電'

df_final.loc[df_final['car_fuel'].str.contains('純電') == True, 'car_fuel'] = '電動'

In [84]:
df_final = df_final.replace({'car_driveMode': r'WD$'}, {'car_driveMode': ''}, regex=True)

In [91]:
df_final['car_driveMode'].unique()

array([ 2.,  4., nan])

In [90]:
df_final['car_driveMode'] = df_final['car_driveMode'].astype(float)

In [95]:
df_final = df_final.replace({'dealer_address': r'\(.*\)|\s-\s.*'}, {'dealer_address': ''}, regex=True)

In [99]:
df_final['car_address'].unique()

array(['高雄市', '台中市', '桃園市', '雲林縣', '嘉義市', '新竹市', '新北市', '台北市', '屏東縣',
       '彰化縣', '嘉義縣', '基隆市', '苗栗縣', '台南市', '南投縣', '宜蘭縣', '新竹縣', '花蓮縣',
       '台東縣', nan, '屏東市'], dtype=object)

In [98]:
df_final.loc[df_final['car_address'].str.contains('彰化市') == True, 'car_address'] = '彰化縣'

df_final.loc[df_final['car_address'].str.contains('員鹿路') == True, 'car_address'] = '彰化縣'
df_final.loc[df_final['car_address'].str.contains('台南市') == True, 'car_address'] = '台南市'
df_final.loc[df_final['car_address'].str.contains('新北市') == True, 'car_address'] = '新北市'
df_final.loc[df_final['car_address'].str.contains('台中市') == True, 'car_address'] = '台中市'
df_final.loc[df_final['car_address'].str.contains('桃園縣') == True, 'car_address'] = '桃園市'
df_final.loc[df_final['car_address'].str.contains('中投東') == True, 'car_address'] = '台中市'
df_final.loc[df_final['car_address'].str.contains('崇德路') == True, 'car_address'] = '台中市'
df_final.loc[df_final['car_address'].str.contains('鶯歌路') == True, 'car_address'] = '桃園市'
df_final.loc[df_final['car_address'].str.contains('國際路') == True, 'car_address'] = '桃園市'
df_final.loc[df_final['car_address'].str.contains('臺中市') == True, 'car_address'] = '台中市'
df_final.loc[df_final['car_address'].str.contains('臺南市') == True, 'car_address'] = '台南市'
df_final.loc[df_final['car_address'].str.contains('臺北市') == True, 'car_address'] = '台北市'
df_final.loc[df_final['car_address'].str.contains('臺東縣') == True, 'car_address'] = '台東縣'
df_final.loc[df_final['car_address'].str.contains('仁愛路') == True, 'car_address'] = np.NaN
df_final.loc[df_final['car_address'].str.contains('三民路') == True, 'car_address'] = np.NaN
df_final.loc[df_final['car_address'].str.contains('文中路') == True, 'car_address'] = np.NaN
df_final.loc[df_final['car_address'].str.contains('仁勇路') == True, 'car_address'] = np.NaN
df_final.loc[df_final['car_address'].str.contains('中華一') == True, 'car_address'] = np.NaN
df_final.loc[df_final['car_address'].str.contains('中山路') == True, 'car_address'] = np.NaN
df_final.loc[df_final['car_address'].str.contains('五權西') == True, 'car_address'] = '台中市'
df_final.loc[df_final['car_address'].str.contains('慈文路') == True, 'car_address'] = np.NaN

In [100]:
df_fianl

NameError: name 'df_fianl' is not defined

In [39]:
df_final.to_csv('../csv/cleaned_csv/dataClean_forPrice_20210724.csv', encoding='utf-8-sig')