In [2]:
import pandas as pd
import numpy as np

In [49]:
df1 = pd.read_csv('../csv/raw_csv/car_isave_all_final_v2.csv', index_col=0)

### clean isave

In [27]:
df1

,dealer_name,car_brand,car_model,car_year,car_address,car_color,car_gear,car_cylinderVolume,car_mileage,皮椅,...,MP3,柴油,ＨＩＤ,鋁圈,car_photo,car_price,car_title,dealer_address,id,verified
0,萬通汽車,LUXGEN,URX,2021年,台中市,白色系,手自排,1798CC,1KM,0.0,...,0.0,0.0,0.0,0.0,https://www.isave.com.tw/public/photo/1323773/...,98 萬,[領牌新車 7人旗艦款 全景天窗 全車環景],台中市西屯區環中路一段2280號,1323773.0,1.0
1,萬通汽車,LUXGEN,URX,2021年,台中市,白色系,手自排,1798CC,1KM,0.0,...,0.0,0.0,0.0,0.0,https://www.isave.com.tw/public/photo/1323761/...,98 萬,[7人座旗艦款 新車 新車價112萬],台中市西屯區環中路一段2280號,1323761.0,1.0
2,辛巴克有限公司,FORD,KUGA,2021年,台中市,白色系,手自排,1999CC,4275KM,1.0,...,1.0,1.0,1.0,1.0,https://www.isave.com.tw/public/photo/1302609/...,109 萬,[榮獲2020年 下半年SAVE認證優良店],台中市烏日區新興路193號,1302609.0,1.0
3,廣一汽車商行,SUZUKI,JIMNY,2021年,嘉義縣,灰色系,自排,1462CC,48KM,0.0,...,0.0,0.0,0.0,1.0,https://www.isave.com.tw/public/photo/1279404/...,已收訂,[好車盡在廣一SAVE卓越店新車車道偏移],嘉義縣水上鄉中山路二段1234號,1279404.0,1.0
4,大信汽車,TOYOTA,COROLLA CROSS,2021年,新北市,白色系,手自排,1798CC,3KM,1.0,...,1.0,0.0,0.0,1.0,https://www.isave.com.tw/public/photo/1276916/...,72.80 萬,[全新未開 新車80萬 現折7萬 免綁全險],新北市泰山區新北大道五段618號,1276916.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,合益汽車,TOYOTA,ALTIS,1990年,高雄市,白色系,手自排,1798CC,KM,1.0,...,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1711,保安汽車,TOYOTA,INNOVA,1990年,台南市,銀色系,自排,2694CC,KM,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1712,鴻揚汽車,SUZUKI,SWIFT,1990年,桃園市,白色系,自排,1490CC,KM,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1713,凱順汽車商行,FORD,FOCUS,1990年,高雄市,黃色系,手排,1999CC,270000KM,0.0,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1714,興達汽車,BENZ,260S,1990年,新北市,NaN,自排,2599CC,KM,1.0,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
#find the data that have price
df1 = df1.loc[df1['car_price'].str.contains('萬') == True]

df1['source'] = 'ISAVE'
df1['car_brand'] = df1['car_brand'].str.upper()
df1['car_model'] = df1['car_model'].str.upper()
df1['car_year'] = df1['car_year'].str.replace('年','')
df1['car_year'] = pd.to_numeric(df1['car_year'])
df1['car_price'] = df1['car_price'].str.replace('萬','').astype(float)*10000
df1['car_cylinderVolume'] = df1['car_cylinderVolume'].str.replace('CC','')
df1['car_cylinderVolume'] = pd.to_numeric(df1['car_cylinderVolume'])
# df1['car_price'] = pd.to_numeric(df1['car_price'])*10000
df1 = df1.replace({'car_color': r'系$'}, {'car_color': ''}, regex=True)
df1 = df1.replace({'car_color': r'色$'}, {'car_color': ''}, regex=True)


car_mileage = []
for i in df1['car_mileage']:
    if i != 'KM':
        tmp = float(str(i).replace('KM',''))#*1000
        car_mileage.append(tmp)

    else:
        tmp = np.NaN
        car_mileage.append(tmp)
df1['car_mileage'] = car_mileage
df1.dropna(subset=['car_mileage','car_price'], inplace=True)  
columns=['car_brand', 'car_model', 'car_year', 'car_mileage', 'car_price', 'car_color', 'car_cylinderVolume', 'car_gear', 'verified', 'source',]
df1 = df1[columns]

In [51]:
df1.head()

,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_cylinderVolume,car_gear,verified,source
0,LUXGEN,URX,2021.0,1.0,980000.0,白,1798.0,手自排,1.0,ISAVE
1,LUXGEN,URX,2021.0,1.0,980000.0,白,1798.0,手自排,1.0,ISAVE
2,FORD,KUGA,2021.0,4275.0,1090000.0,白,1999.0,手自排,1.0,ISAVE
4,TOYOTA,COROLLA CROSS,2021.0,3.0,728000.0,白,1798.0,手自排,1.0,ISAVE
10,HONDA,TYPE R,2021.0,112.0,2280000.0,白,1996.0,手排,0.0,ISAVE

In [52]:
df1.to_csv('../csv/cleaned_csv/car_isave_cleaned_20210722.csv', encoding='utf_8_sig')

### clean abc

In [3]:
df2 = pd.read_csv('../csv/raw_csv/ABC_CAR_final.csv', index_col=0)

In [4]:
pd.set_option('max_columns', None)
df2

,car_photo,car_price,car_title,dealer_address,dealer_name,verified,car_brand,car_model,id,car_year,car_mileage,car_address,car_cylinderVolume,car_gear,car_driveMode,car_color,car_fuel,car_seat,sunroof,HID,LED,leather_seat,electric_seat,keyless,IVI_sys,auto_AC,navi_sys,SW_button,EPB,electric_slidingdoor,日行燈,ABS,SRS,TCS,TPMS,parking_camera,cruise_sys,BSM,LDW,ACC主動定速
0,https://img.abccar.com.tw/resize?key=650x435/h...,71.8萬,TOYOTA RAV4 2.0 E (4代)2017,賞車地址：南投縣草屯鎮太平路一段9號,TOYOTA認證中古車/中誠草屯所,1,TOYOTA,RAV4 2.0 E (4代),物件編號1566744,2017年11月,"81,691公里",南投縣,2L,CVT 無段變速,前輪驅動,NaN,汽油,5人,0,0,1,1,1,1,0,0,1,0,0,0,0,1,1,1,1,1,0,0,1,1
1,https://img.abccar.com.tw/resize?key=650x435/h...,38.8萬,TOYOTA Corolla Altis 1.8 雅緻版 (11代)2013,賞車地址：雲林縣斗六市明德北路三段280號,TOYOTA認證中古車/南都斗六所,1,TOYOTA,Corolla Altis 1.8 雅緻版 (11代),物件編號1567986,2013年08月,"100,515公里",雲林縣,1.8L,手自排,前輪驅動,NaN,汽油,5人,0,0,0,1,0,0,1,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0
2,https://img.abccar.com.tw/resize?key=650x435/h...,32.8萬,TOYOTA Yaris 1.5 E (2代)2013,賞車地址：彰化縣花壇鄉中山路一段93-1號,TOYOTA認證中古車/中誠彰化所,1,TOYOTA,Yaris 1.5 E (2代),物件編號1550919,2013年01月,"127,095公里",彰化縣,1.5L,自排,前輪驅動,NaN,汽油,5人,0,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
3,https://img.abccar.com.tw/resize?key=650x435/h...,116.8萬,LEXUS RX350 頂級版 (3代)2015,賞車地址：新北市樹林區中正路421號,小鍾,0,LEXUS,RX350 頂級版 (3代),物件編號1568145,2015年11月,"53,004公里",新北市,3.5L,手自排,四輪驅動,紅色,汽油,5人,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1
4,https://img.abccar.com.tw/resize?key=650x435/h...,23.8萬,LUXGEN 7 MPV 精緻型 8人座2012,賞車地址：新北市樹林區大安路558號,宋小姐,0,LUXGEN,7 MPV 精緻型 8人座,物件編號1531069,2012年12月,"250,000公里",新北市,2.2L,手自排,前輪驅動,白色,汽油,8人(含以上),0,0,0,1,0,1,0,1,0,0,0,0,0,1,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4610,https://img.abccar.com.tw/resize?key=650x435/h...,69.8萬,SUBARU Impreza 5D 1.6i-S (5代)2017,賞車地址：新北市板橋區文化路一段201-1號,郭麟政,0,SUBARU,Impreza 5D 1.6i-S (5代),物件編號1496545,2017年08月,"66,000公里",新北市,1.6L,CVT 無段變速,四輪驅動,白色,汽油,5人,1,1,0,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,0,0
4611,https://img.abccar.com.tw/resize?key=650x435/h...,11萬,LEXUS RX330 (2代)2003,賞車地址：新北市樹林區新北市樹林區樹新路107號,蔡先生,0,LEXUS,RX330 (2代),物件編號1531472,2003年04月,16公里,新北市,3.3L,手自排,四輪驅動,棕色,汽油,5人,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4612,https://img.abccar.com.tw/resize?key=650x435/h...,35萬,Mazda 3 5D2017,賞車地址：新北市五股區成泰路三段,何小姐,0,Mazda,3 5D,物件編號1565354,2017年10月,"11,117公里",新北市,2L,手自排,前輪驅動,白色,汽油,5人,0,0,1,1,1,1,1,1,1,1,0,0,0,1,1,1,0,1,1,0,0,0
4613,https://img.abccar.com.tw/resize?key=650x435/h...,37萬,SUZUKI Swift 1.2 GLX2015,賞車地址：新北市蘆洲區三民路86-2號,戴楷文,0,SUZUKI,Swift 1.2 GLX,物件編號1528081,2015年05月,"50,000公里",新北市,1.2L,自排,前輪驅動,藍色,汽油,5人,0,1,1,1,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,0,0
4614,https://img.abccar.com.tw/resize?key=650x435/h...,168萬,Porsche Cayenne Diesel (Mk2)2014,賞車地址：新北市林口區文化北路二段198號,值班人員,0,Porsche,Cayenne Diesel (Mk2),物件編號1539171,2014年12月,"90,000公里",新北市,3L,手自排,四輪驅動,白色,柴油,5人,0,1,0,1,1,0,1,1,0,1,1,0,1,1,0,1,1,0,1,0,0,0

In [5]:
columns=['car_brand', 'car_model', 'car_year', 'car_mileage', 'car_price', 'car_color', 'car_seat','car_cylinderVolume', 'car_driveMode', 'car_fuel', 'car_gear', 'verified']
df2=df2[columns]

In [6]:
df2['car_seat'].unique()

array(['5人', '8人(含以上)', '7人', '3人', '2人', '4人', nan, '6人'], dtype=object)

In [7]:
#find the data that have price

df2 = df2.loc[df2['car_price'].apply(str).str.contains('Error') == False]
df2 = df2.loc[df2['car_price'].str.contains('萬') == True]

df2['source'] = 'ABC_CAR'
df2['car_mileage'] = df2['car_mileage'].str.replace('公里','')
df2 = df2.replace({'car_mileage':','}, {'car_mileage':''}, regex=True)
df2['car_mileage'] = df2['car_mileage'].astype(int)
df2 = df2.replace({'car_driveMode':'前輪驅動'}, {'car_driveMode':2}, regex=True)
df2 = df2.replace({'car_driveMode':'後輪驅動'}, {'car_driveMode':2}, regex=True)
df2 = df2.replace({'car_driveMode':'四輪驅動'}, {'car_driveMode':4}, regex=True)



df2 = df2.replace({'car_seat':'人$'}, {'car_seat':''}, regex=True)
df2.loc[df2['car_seat'].str.contains('以上') == True, 'car_seat'] = 8
df2['car_seat'] = df2['car_seat'].astype(float)
df2 = df2.replace({'car_color':'色$'}, {'car_color':''}, regex=True)

df2 = df2.replace({'car_cylinderVolume':r'L$'}, {'car_cylinderVolume': ''}, regex=True)
df2['car_cylinderVolume'] = ((df2['car_cylinderVolume'].astype(float))*1000).astype(int)


df2['car_brand'] = df2['car_brand'].str.upper()
df2['car_model'] = df2['car_model'].str.upper()
df2['car_year'] = df2['car_year'].str.split('年',1).str[0]
df2['car_year'] = pd.to_numeric(df2['car_year'])
df2['car_price'] = df2['car_price'].str.replace('萬','')
df2['car_price'] = pd.to_numeric(df2['car_price'])*10000
df2.loc[df2['verified'].str.contains('badge') == True, 'verified'] = 0
df2['verified'] = df2['verified'].astype(int)
df2

,car_brand,car_model,car_year,car_mileage,car_price,car_color,car_seat,car_cylinderVolume,car_driveMode,car_fuel,car_gear,verified,source
0,TOYOTA,RAV4 2.0 E (4代),2017,81691,718000.0,NaN,5.0,2000,2.0,汽油,CVT 無段變速,1,ABC_CAR
1,TOYOTA,COROLLA ALTIS 1.8 雅緻版 (11代),2013,100515,388000.0,NaN,5.0,1800,2.0,汽油,手自排,1,ABC_CAR
2,TOYOTA,YARIS 1.5 E (2代),2013,127095,328000.0,NaN,5.0,1500,2.0,汽油,自排,1,ABC_CAR
3,LEXUS,RX350 頂級版 (3代),2015,53004,1168000.0,紅,5.0,3500,4.0,汽油,手自排,0,ABC_CAR
4,LUXGEN,7 MPV 精緻型 8人座,2012,250000,238000.0,白,8.0,2200,2.0,汽油,手自排,0,ABC_CAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4610,SUBARU,IMPREZA 5D 1.6I-S (5代),2017,66000,698000.0,白,5.0,1600,4.0,汽油,CVT 無段變速,0,ABC_CAR
4611,LEXUS,RX330 (2代),2003,16,110000.0,棕,5.0,3300,4.0,汽油,手自排,0,ABC_CAR
4612,MAZDA,3 5D,2017,11117,350000.0,白,5.0,2000,2.0,汽油,手自排,0,ABC_CAR
4613,SUZUKI,SWIFT 1.2 GLX,2015,50000,370000.0,藍,5.0,1200,2.0,汽油,自排,0,ABC_CAR
4614,PORSCHE,CAYENNE DIESEL (MK2),2014,90000,1680000.0,白,5.0,3000,4.0,柴油,手自排,0,ABC_CAR

In [101]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27282 entries, 0 to 4614
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   car_brand           27282 non-null  object
 1   car_model           27282 non-null  object
 2   car_year            27282 non-null  int64
 3   car_mileage         27282 non-null  int64
 4   car_price           27282 non-null  float64
 5   car_color           26471 non-null  object
 6   car_seat            26917 non-null  float64
 7   car_cylinderVolume  27282 non-null  int64
 8   car_driveMode       26933 non-null  float64
 9   car_fuel            26915 non-null  object
 10  car_gear            26927 non-null  object
 11  verified            27282 non-null  int64
 12  source              27282 non-null  object
dtypes: float64(3), int64(4), object(6)
memory usage: 2.9+ MB

In [8]:
df2.to_csv('../csv/cleaned_csv/abc_car_cleaned_20210722.csv', encoding='utf_8_sig')